### PR TITLE
FIX: GMM parameters on correct device

### PR DESCRIPTION
**Pull request by brudfors**

### CODE REVIEW

**Comment by balbasty** [comment]
I Imaging the code was erroring before your fix, but I don't understand why. `mu` and `sigma` are computed _from_ `x`, so they should have the same dtype and device already.

**Comment by brudfors** [comment]
I think maybe that I could instead have done:
```py
edges = torch.linspace(mn[c], mx[c], nk+1, device=device)
```
I will fix that.

**Comment by balbasty** [comment]
But `mn` and `mx` should already have the correct device, no?

**Comment by brudfors** [comment]
I think it is because inputs to `linspace` are read as floats: https://pytorch.org/docs/stable/generated/torch.linspace.html

**Comment by balbasty** [comment]
Oh! Should we also set the dtype then? In case `x.dtype` is not `torch.get_default_dtype()`?

**Comment by brudfors** [comment]
Good idea! Done.

**Pull request merged**
