### PR TITLE
Expose steps parameter in SynthFromLabelTransform

### PR DESCRIPTION
**Pull request by brudfors**
* Allows for exponentiating a stationary velocity field by scaling and squaring
* Set to zero be default, meaning no scaling and squaring

### CODE REVIEW

**Comment by brudfors** [comment]
@balbasty, the `steps` parameter is now exposed. However, `warps.exp_velocity` is never [triggered](https://github.com/brudfors/cornucopia/blob/expose-steps/cornucopia/geometric.py#L100), as `fullsize` is hardcoded to `False` on [this line](https://github.com/brudfors/cornucopia/blob/expose-steps/cornucopia/geometric.py#L398). Setting `fullsize=True` gives a runtime error. Any idea what is going on here?

**Comment by balbasty** [comment]
I remember now. The difficulty is that exponentiation involves the entire FOV. It clashes with the use of the `patch` option, whose whole point is to avoid calculating the hires displacement on the entire field of view.

It may be possible to evaluate the displacement on a bigger patch (larger than the target patch, but smaller than the entire FOV) and perform the exponentiation there. But I wonder if it's worth the trouble. What do you think?

**Comment by brudfors** [comment]
I guess the main question is: would `steps>0` even give better results?

**Comment by balbasty** [comment]
We can try your idea (deactivate `steps` if `patch` is used), at least temporarily for testing. If it's not useful for performance, it's maybe better to not expose it.

**Comment by brudfors** [comment]
I will keep testing in my own branch for then, will let you know how it goes.

**Comment by brudfors** [comment]
Also please double check what how I added the full sized displacement looks OK. It runs fine on my end and looks good.

**Comment by balbasty** [comment]
Replaced by PR #4

**Pull request closed without merging**
